name: notary_office_app
description: "تطبيق إدارة مكتب موثق جزائري مع واجهة حديثة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1  # لإدارة الحالة
  intl: ^0.19.0  # للتنسيق والتواريخ

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # دعم اللغة العربية (RTL)
  assets:
    - assets/fonts/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700